{% set name = "numba" %}
{% set version = "0.56.3" %}
{% set sha256 = "8c8957219e0356cc82d366fcde13a797c329c0fc8ed4c13fdf748265922a28d5" %}

package:
  name: numba
  version: {{ version }}

source:
  url: https://github.com/numba/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - pycc = numba.pycc:main
    - numba = numba.misc.numba_entry:main
  script:
    - export CC="${CC} -pthread"  # [linux]
    - export CXX="${CXX} -pthread"  # [linux]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  # ignore_run_exports:
  #  # tbb-devel triggers hard dependency on tbb, this is not the case.
  #  - tbb
  skip: true  # [python_impl == 'pypy']
  skip: true  # [py<37 or s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # llvm is needed for the headers
    - llvm-openmp              # [osx]

  host:
    - python
    - pip
    - setuptools
    - wheel
    - llvmlite 0.39.*
    - numpy >=1.18,!=1.22.0,!=1.22.1,!=1.22.2,<1.23
    - tbb-devel 2021.*,<2021.6
    - _openmp_mutex            # [linux]
    - importlib_metadata       # [py<39]

  run:
    - python
    - importlib_metadata       # [py<39]
    - llvmlite >=0.39.*,<0.40
    # NumPy has a hard upper limit.
    # NumPy 1.22.0, 1.22.1, 1.22.2 are all broken for ufuncs
    # xref: https://github.com/numba/numba/issues/7756
    # NumPy >=1.23 breaks with CUDA test: test_reinterpret_array_type
    # xref: https://github.com/numba/numba/issues/8529
    - numpy >=1.18,!=1.22.0,!=1.22.1,!=1.22.2,<1.23
    # needed for pkg_resources
    - setuptools

  run_constrained:
    - tbb  >=2021.0
    # avoid confusion from openblas bugs
    - libopenblas !=0.3.6      # [x86_64]
    - libopenblas >=0.3.18, !=0.3.20  # [arm64]
    # CUDA 10.2 or later is required for CUDA support
    - cudatoolkit >=10.2
    # scipy 1.0 or later
    - scipy >=1.0
    # CUDA Python 11.6 or later
    - cuda-python >=11.6

test:
  requires:
    # Required to test optional Numba features
    - jinja2
    - cffi
    - scipy
    - ipython
    - ipykernel
    - pygments
    - pexpect
    - setuptools
    - pip
    - wheel
    - tbb >=2021.0
    - llvm-openmp              # [osx]
    # Need these for AOT. Do not init msvc as it may not be present
    - {{ compiler('c') }}      # [not win]
    - {{ compiler('cxx') }}    # [not win]

  imports:
    - numba
    - numba.core.annotations
    - numba.core.datamodel
    - numba.core.rewrites
    - numba.core.runtime
    - numba.core.typeconv
    - numba.core.typing
    - numba.core.unsafe
    - numba.cuda
    - numba.cuda.cudadrv
    - numba.cuda.kernels
    - numba.cuda.simulator
    - numba.cuda.simulator.cudadrv
    - numba.cuda.tests
    - numba.cuda.tests.cudadrv
    - numba.cuda.tests.cudadrv.data
    - numba.cuda.tests.cudapy
    - numba.cuda.tests.cudasim
    - numba.cuda.tests.nocuda
    - numba.experimental.jitclass
    - numba.np.ufunc
    - numba.pycc
    - numba.scripts
    - numba.testing
    - numba.tests
    - numba.tests.npyufunc

about:
  home: https://numba.pydata.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  license_url: https://github.com/numba/numba/blob/{{ version }}/LICENSE
  summary: NumPy aware dynamic Python compiler using LLVM
  description: |
    Numba is an Open Source NumPy-aware optimizing compiler for Python 
    sponsored by Anaconda, Inc. It uses the remarkable LLVM compiler 
    infrastructure to compile Python syntax to machine code."
  dev_url: https://github.com/numba/numba
  doc_url: https://numba.pydata.org/
  doc_source_url: https://github.com/numba/numba/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - souravsingh
    - marcelotrevisani
    - henryiii
    - mbargull
    - jakirkham
    - step21
