{% set name = "numba" %}
{% set version = "0.62.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/numba/numba.git
  git_tag: {{ version }}
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: 8750ee147940a6637b80ecf7f95062185ad8726c8c28a2295b8ec1160a196f7d

build:
  number: 0
  skip: true  # [py<310 or py>=314]
  script:
    - export CC="${CC} -pthread"  # [linux]
    - export CXX="${CXX} -pthread"  # [linux]
    - {{ PYTHON }} -m pip install . --no-deps  --no-build-isolation --ignore-installed -vv
  entry_points:
    - numba = numba.misc.numba_entry:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    # llvm is needed for the headers
    - llvm-openmp 20          # [osx]
  host:
    - python
    - pip
    - setuptools
    - llvmlite 0.45.0rc2
    - numpy >=2.0.0rc1,<2.4
    - numpy {{ numpy }}
    - tbb-devel 2022.0.0
    - _openmp_mutex 5.1        # [linux]
  run:
    - python
    - llvmlite >=0.44.0dev0,<0.45
    # avoid 2.0.1 because of https://github.com/numpy/numpy/pull/27195
    - numpy >=1.22,<2.4,!=2.0.1
  run_constrained:
    - tbb >=2022
    # avoid confusion from openblas bugs
    - libopenblas !=0.3.6      # [x86_64]
    - libopenblas >=0.3.18, !=0.3.20  # [arm64]
    # CUDA 11.2 or later is required for CUDA support
    - cuda-version >=11.2
    - cudatoolkit >=11.2
    # scipy 1.0 or later
    - scipy >=1.0
    # CUDA Python 11.6 or later
    - cuda-python >=11.6
    # numba-rvsdg
    - numba-rvsdg 0.0.*      # [py==311]

test:
  requires:
    - pip
    - jinja2
    # Required to test optional Numba features
    - cffi
    - scipy
    - ipython
    - ipykernel
    # for pycc
    - setuptools
    - pygments
    - pexpect
    - tbb
    # Need these for AOT.
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}

  imports:
    - numba
    - numba.core.annotations
    - numba.core.datamodel
    - numba.core.rewrites
    - numba.core.runtime
    - numba.core.typeconv
    - numba.core.typing
    - numba.core.unsafe
    - numba.cuda
    - numba.cuda.cudadrv
    - numba.cuda.kernels
    - numba.cuda.simulator
    - numba.cuda.simulator.cudadrv
    - numba.cuda.tests
    - numba.cuda.tests.cudadrv
    - numba.cuda.tests.data
    - numba.cuda.tests.cudapy
    - numba.cuda.tests.cudasim
    - numba.cuda.tests.nocuda
    - numba.experimental.jitclass
    - numba.np.ufunc
    - numba.pycc
    - numba.scripts
    - numba.testing
    - numba.tests
    - numba.tests.npyufunc

about:
  home: https://numba.pydata.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: NumPy aware dynamic Python compiler using LLVM
  description: |
    Numba is an Open Source NumPy-aware optimizing compiler for Python
    sponsored by Anaconda, Inc. It uses the remarkable LLVM compiler
    infrastructure to compile Python syntax to machine code."
  dev_url: https://github.com/numba/numba
  doc_url: https://numba.readthedocs.io/

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - souravsingh
    - marcelotrevisani
    - henryiii
    - mbargull
    - jakirkham
    - step21
