travis:
  secure:
    BINSTAR_TOKEN: PiKYRfjNfAkVeaNWljxf1wGo6nDHryYFmKDuwo4WHcznjObhRXkMjt20CBMr5eP5W8/PjJmv93BVHNijXDGYtOijNHpUOfoUbKJBBXIMuusbem5j4SYqv5WQSL0D26JrNzw8eY38UtABnAW/OKtbQDwH9Ndl9fvvCo9V13U4bmJ8oXB3d7VfwrLaJObcs0aK8S97h7diRC9dukHLSZm+0G8j77v1enS4VlPCvkZe1iJQu64mY2fZndLqKzRWlgpSO3SgyHi/3EmJlbZTF7LQIoWcf8NCvFZxadghM+lyQWhhtaw7FN5npsOK86S4yV3+NMWiKdB02MxZpF0ytg0Z50vh6l7yksGYbssIM0OAM6JMdfy1O/J6uSezJODuXOLiLEYOfepVqd9EHAwtA1i+vz4aQO9PF+3i7LKJoX06hgA3PfWj64kSgjT0LJyV1KlyzxhzwVfn7/SO7MU73oejdSIyOMYqH3bEqcmxvxESc7dQQ/CdUMfHcjv5WFRgjep5HVdWECvGgdcQfDRLLILrqxpv50iaRt6RO0QSgHRbWRU70Gfd8OqecuVPPVh6MN4cqlAoC7BExvtfSc3PcGMQDWScg4zK4kOcOxLCULcfz1lZqViCDBq1omkSmMSbkLPzYNf2NnENG+wdlsACFrD3Q9Gm5kzB4qEflhMphq2yhWI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
